#! /bin/bash

result_file="../hw1test/result"

cd ../hw1
echo -e "\e[1;33m--- Test Result ---\e[m" > $result_file

for i in `seq 1 8`; do
	echo "Testing $i thread..."
	make THREAD=$i
	echo "Result for $i thread: " >> $result_file
	/usr/bin/time -a -p -o $result_file ./hw1_pthread $1 >> $result_file
	make clean
	echo >> $result_file
done

cat $result_file | grep -v -e "user" -e "sys"
cd ../hw1test
